# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_workplace', models.CharField(max_length=30)),
                ('contact_mobile', models.CharField(max_length=30)),
                ('contact_website', models.CharField(max_length=30)),
                ('contact_type', models.CharField(max_length=30)),
                ('bill_attention', models.CharField(max_length=30)),
                ('bill_address1', models.CharField(max_length=30)),
                ('bill_address2', models.CharField(max_length=30)),
                ('bill_city', models.CharField(max_length=30)),
                ('bill_state', models.CharField(max_length=30)),
                ('bill_zip', models.CharField(max_length=30)),
                ('bill_country', models.CharField(max_length=30)),
                ('bill_fax', models.CharField(max_length=30)),
                ('bill_phone', models.CharField(max_length=30)),
                ('ship_attention', models.CharField(max_length=30)),
                ('ship_address1', models.CharField(max_length=30)),
                ('ship_address2', models.CharField(max_length=30)),
                ('ship_city', models.CharField(max_length=30)),
                ('ship_state', models.CharField(max_length=30)),
                ('ship_zip', models.CharField(max_length=30)),
                ('ship_country', models.CharField(max_length=30)),
                ('ship_fax', models.CharField(max_length=30)),
                ('ship_phone', models.CharField(max_length=30)),
            ],
        ),
    ]
