# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171216_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=30, null=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=30, null=True)),
                ('sale_account', models.CharField(blank=True, max_length=30, null=True)),
                ('sale_desc', models.CharField(blank=True, max_length=30, null=True)),
                ('tax', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_account', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_desc', models.CharField(blank=True, max_length=30, null=True)),
                ('inv_account', models.CharField(blank=True, max_length=30, null=True)),
                ('inv_reorder_level', models.CharField(blank=True, max_length=30, null=True)),
                ('inv_opening_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('inv_opening_stock_value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
