# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(blank=True, max_length=30, null=True)),
                ('so_customer', models.CharField(blank=True, max_length=30, null=True)),
                ('so_reference', models.CharField(blank=True, max_length=30, null=True)),
                ('so_date', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
