# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='so_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
