# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salesorder_so_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(blank=True, max_length=30, null=True)),
                ('so_item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('so_item_qty', models.CharField(blank=True, max_length=30, null=True)),
                ('so_item_rate', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
