# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171227_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='so_item_name',
            new_name='so_item_id',
        ),
    ]
