# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171227_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
