# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171228_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group_id', models.CharField(blank=True, max_length=30, null=True)),
                ('item_group_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
